### PR TITLE
[CI] Release Workflow

### PR DESCRIPTION
**Pull request by jamesb93**
Adds support for manually releasing via a github workflow dispatch.﻿

### CODE REVIEW

**Comment by tremblap** [comment]
the uncompressed folder is not included in an encapsulating folder "FluidCorpusManipulation" like the other releases

**Comment by jamesb93** [comment]
> the uncompressed folder is not included in an encapsulating folder "FluidCorpusManipulation" like the other releases

Hence draft status of PR :P I was testing how tinkerable the `workflow_dispatch` API was and just wanted to see if it would build from the main branch (instead of dev)

**Comment by jamesb93** [comment]
> the uncompressed folder is not included in an encapsulating folder "FluidCorpusManipulation" like the other releases

My mistake, what you are seeing is not related to this PR right now. The bin, docs etc should end up in a folder like the other ones for consistency. PR inc.

**Comment by jamesb93** [comment]
I got you @tremblap: https://github.com/flucoma/flucoma-cli/pull/22

**Pull request closed without merging**
