### PR TITLE
Updates for hisstools library header-only

### PR DESCRIPTION
**Pull request by AlexHarker**
This is the update for CLI to move to hisstools library header-only

### CODE REVIEW

**Comment by AlexHarker** [comment]
needed for https://github.com/flucoma/flucoma-core/pull/265

**Comment by tremblap** [comment]
oh I should have meetings more often. things happen by magic!

**Comment by tremblap** [comment]
I'll listen to bufnmf null summing as audio out sanity test?

**Review by tremblap — CHANGES_REQUESTED** [review]
I get a lot of these errors:

/research/dependencies/hisstools-src/include/audio_file/out_file.hpp:230:36: error: use of undeclared identifier 'endianness'
        if (header_endianness() == endianness::little)
                                   ^

**Comment by tremblap** [comment]
(helping me to find the answer would be appreciated if you have the time to be verbose - I aim to improve my independence)

**Comment by tremblap** [comment]
ok i tried and it seems to be an error in the header file out_file.hpp that I cannot correct...

**Comment by tremblap** [comment]
should it be m_endianness instead?

**Comment by tremblap** [comment]
actually, I replaced endianness:: with endian_type:: and it works

**Comment by tremblap** [comment]
next bug: 

FluidCLIWrapper.hpp:97:19: error: too few arguments to function call, single argument 'position' was not specified
        file.seek();
        ~~~~~~~~~ ^
/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/dependencies/hisstools-src/include/audio_file/out_file.hpp:76:10: note: 'seek' declared here
    void seek(uintptr_t position)

**Comment by tremblap** [comment]
ok so I missed the memo - it seems to work with the pull to the changes in HISStools and I'm chasing bugs that were sorted - but there is no note here that I should have pulled, hence the ghost chasing!

**Comment by tremblap** [comment]
ok real problem now: no more null-summing.

- download the CLI version, run HPSS with default settings, it nullsums in reaper
- with the latest compile of header only, it doesn't - I suspect bit resolution size is not behaving as it is all in the top end

**Comment by tremblap** [comment]
both are 32 bit float, so that is not the problem. Here is the output of afinfo on both versions - so it might be in the reading or the handling of the audio. I will stop pretending to troubleshoot but there is something not happy with file i/o 

pa@tas ~ % afinfo /Users/pa/Desktop/h.wav
File:           /Users/pa/Desktop/h.wav
File type ID:   WAVE
Num Tracks:     1
----
Data format:     1 ch,  44100 Hz, Float32
                no channel layout.
estimated duration: 10.293243 sec
audio bytes: 1815728
audio packets: 453932
bit rate: 1411200 bits per second
packet size upper bound: 4
maximum packet size: 4
audio data file offset: 44
optimized
source bit depth: F32
----
pa@tas ~ % afinfo /Users/pa/Desktop/h\ copy.wav
File:           /Users/pa/Desktop/h copy.wav
File type ID:   WAVE
Num Tracks:     1
----
Data format:     1 ch,  44100 Hz, Float32
                no channel layout.
estimated duration: 10.293243 sec
audio bytes: 1815728
audio packets: 453932
bit rate: 1411200 bits per second
packet size upper bound: 4
maximum packet size: 4
audio data file offset: 44
optimized
source bit depth: F32
----

**Comment by tremblap** [comment]
I found the bug - there is a one sample offset in either input or output but I get 1 sample earlier with the new version

**Comment by tremblap** [comment]
Screenshot 2024-03-01 at 13 16 27

**Comment by AlexHarker** [comment]
Thanks - is this a change of behaviour from the previous version?

**Comment by tremblap** [comment]
yes, the lined up file in the picture is yesterday's nightly. the only diffs are in core and here relating to the header-only hiss-magic

**Comment by AlexHarker** [comment]
Please redo all your cmake and test again - this should now be fixed (with core pulling in the fix)

**Comment by tremblap** [comment]
it all works thanks

**Pull request merged**
